name       : vocal
homepage   : http://vocalproject.net/
version    : 2.1.5
release    : 6
source     :
    - https://github.com/needle-and-thread/vocal/archive/2.1.5.tar.gz : 83d800c813a32a9d7ab3385edf04361e9a5e68ba055af20d211e1623a2e27027
license    : GPL-3.0
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
