name       : vocal
homepage   : http://vocalproject.net/
version    : 2.0.1
release    : 5
source     :
    - https://github.com/needle-and-thread/vocal/archive/2.0.20.tar.gz : 32219106bf085d43d710986d346b3ceaf01958d90e2cd8e2400963edf13c1358
license    : GPL-3.0
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
