name       : vocal
homepage   : http://vocalproject.net/
version    : 2.4.2
release    : 15
source     :
    - https://github.com/needle-and-thread/vocal/archive/2.4.2.tar.gz : be1991f08db05feacad30a0f459002327ba5ff3cb04757383f1da62904acdb41
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
