name       : vocal
homepage   : http://vocalproject.net/
version    : 2.4.0
release    : 13
source     :
    - https://github.com/needle-and-thread/vocal/archive/2.4.0.tar.gz : d343ddb5c1bdc167fc34ac3300b0d108cc3fdae102ee0c6a3b258a922b8a2af8
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
