name       : vocal
homepage   : http://vocalproject.net/
version    : 1.0
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/vocalpodcast/vocal_1.0.tar.gz : cab0702c25231037e05017ded1c0b2f08a1a789caa8130a064392942d97423e6
license    : GPL-3.0
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libnotify)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
