name       : vocal
homepage   : http://vocalproject.net/
version    : 2.1.6
release    : 8
source     :
    - https://github.com/needle-and-thread/vocal/archive/2.1.6.tar.gz : 554f88cef53975e8d4b7c61525e0068b21af2ba76f1e81080d2650e895958acf
license    : GPL-3.0
component  : multimedia.audio
summary    : The podcast client for the modern free desktop.
description: |
    A GTK3.14 podcast client for the modern free desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - granite-devel
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
